### ISSUE TITLE
Sublime YAML file format

### ISSUE THREAD

**Issue by tobiasvl** [mattmikolay/octo-sublime#5]
As far as I can tell, the YAML Sublime syntax file "should" be named `Octo.sublime-syntax` rather than `Octo.YAML-tmLanguage` in order to follow the Sublime naming standard?

I haven't used Sublime Text itself, so I suppose it can load files that are named anything, but I've looked at a few syntax highlighting libraries that make it very convenient to load files with the extension `.sublime-syntax`, and not so easy to load files named other things (such as [syntect](https://github.com/trishume/syntect), which can scan directories for files with that extension).

**Comment by tobiasvl** [comment]
Oh, wait. It seems `.sublime-syntax` and `.YAML-tmLanguage` files are similar, but subtly different, formats. I thought the YAML version of the tmLanguage file _was_ the Sublime version, but I guess `.sublime-syntax` is a Sublime 3 thing. https://www.sublimetext.com/docs/syntax.html

**Comment by tobiasvl** [comment]
FWIW, it seems like the differences between the two formats are pretty minor. I managed to convert the `.YAML-tmLanguage` to a `.sublime-syntax` file that syntect parses, by changing a few attribute/key names and structure the file a little differently.

Not sure if it's a good idea to put _another_ version of the syntax file that needs to be manually maintained in the repo, if the `.YAML-tmLanguage` file in the repo should just be converted to a `.sublime-syntax` file, or if I should maintain my own `.syntax-sublime` file manually on the side.

I'll reopen and rename the issue just in case you have an opinion on this.

**Comment by mattmikolay** [comment]
Apologies for the delay here. @tobiasvl, would it be possible for you to post a PR that replaces the `.YAML-tmLanguage` file with the `.sublime-syntax` version? The [Sublime Text Community Documentation](https://docs.sublimetext.io/guide/extensibility/syntaxdefs.html) mentions that the `.tmLanguage` format (which is generated from the `.YAML-tmLanguage` file) has been deprecated:

> For Sublime Text 3 (Build 3084), a new syntax definition format has been added with the `.sublime-syntax` extension.
>
> It is highly encouraged to be used in favor of the legacy TextMate format described in this document, unless compatibility with older versions or other editors is desired.

I'd be surprised if anyone is using octo-sublime with Sublime Text 2.

Thanks!

**Comment by tobiasvl** [comment]
@mattmikolay Sure: #6
